#!/usr/bin/env bash
#
# This depends on genisoimage: yum install genisoimage

set -o errexit
set -o pipefail
if [[ -n "$TRACE" ]]; then set -o xtrace; fi
set -o nounset

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    cat <<EOF
Usage: $0 VM-UUID path/to/dir

Create an ISO from a directoty and make it available as a CD for a VM.
EOF
exit 0
fi

VM=${1:?Provide the UUID of the VM}
DIR=${2:?Provide the path to a directory containing configuration data}

now=$(date +%Y%m%d-%H%M%S)

if ! test -d "$DIR"; then
  echo "$DIR is not a directory"
  exit 1
fi

# Create ISO with content
img="config-$VM.iso"
sr_dir="/var/opt/iso"

# Create a local ISO SR
mkdir -p "$sr_dir" || true
genisoimage -J -o "$sr_dir/$img" "$DIR"
NAME="CONFIG"

SR=$(xe sr-list name-label="$NAME" params=uuid minimal=true)
if test -z "$SR"; then
  echo "Creating new local SR"
  SR=$(xe sr-create \
    name-label="$NAME" \
    device-config:location=$sr_dir \
    device-config:legacy_mode=true \
    type=iso \
    content-type=iso)
else
  echo "Using existing local SR $SR"
fi

xe sr-scan uuid="$SR"
# find the first DVD drive and insert the ISO
VDI=$(xe vdi-list name-label=$img minimal=true)
VBD=$(xe vm-cd-list uuid="$VM" minimal=true | tr ',' \\012 | head -1)
xe vbd-insert uuid="$VBD" vdi-uuid="$VDI"

ID=$(xe vm-list \
  uuid="$VM" \
  params="dom-id" \
  minimal=true)

# tell the VM
XS="/local/domain/$ID/control/sysprep"
xenstore-write "$XS/filename" "D://unattend.xml"
xenstore-write "$XS/action"   "sysprep"









